services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=project_db
      - DB_USERNAME=project_user
      - DB_PASSWORD=project_password
    depends_on:
      - db
    networks:
      - app_network

  nuxt:
    build:
      context: ./web
      dockerfile: ../docker/nuxt/Dockerfile
    container_name: nuxt_app
    volumes:
      - ./web:/usr/src/app
    ports:
      - "4000:3000"
    environment:
      - NUXT_PORT=3000
      - NODE_ENV=development
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html/public
    networks:
      - app_network
    depends_on:
      - app
      - nuxt

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: project_db
      MYSQL_USER: project_user
      MYSQL_PASSWORD: project_password
    ports:
      - "4306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: